# Generated by Django 5.2.5 on 2025-08-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='ammont',
            field=models.FloatField(),
        ),
    ]
