# Generated by Django 5.2.5 on 2025-08-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expense_ammont'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='ammont',
        ),
        migrations.AddField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=7),
        ),
    ]
